export default actionType = {
    HANDLE_AUTHN: 'handle_authn',
    LOGOUT: 'logout',
    RETURN_SEARCH_ITEMS: 'return_search_items',
    RETURN_ID_SEARCH_ITEMS: 'return_id_search_items',
    RETURN_EVENTS: 'return_events',
    RETURN_LOW_STOCK_PRODUCTS: 'return_low_stock_products',
    SET_EVENT: 'set_event',
    UPDATE_USERID: 'update_userid',
    ADD_TO_CART: 'add_to_cart',
    DECREMENT_FROM_CART: 'decrement_from_cart',
    REMOVE_FROM_CART: 'remove_from_cart',
    EMPTY_CART: 'empty_cart',
    CHECKOUT: 'checkout',
    CLEAR_STATE_ON_LOGOUT: 'clear_state_on_logout',
    UPDATE_SALESQUEUE_ORDER_WITH_ID: 'update_order_with_id',
    REMOVE_FIRST_ITEM_FROM_SALES_QUEUE: 'remove_item_from_sales_queue',
    SUBMIT_COMMISSION: 'submit_commission',
    REMOVE_COMMISSION_FROM_QUEUE: 'remove_commission_from_queue',
    UPDATE_USER_EVENT_SALES: 'update_user_event_sales', //every time you sync a new order, makes your sales tab re-render (??)
    SET_LOW_STOCK_PRODUCTS_UPDATED: 'set_low_stock_products_updated',
    UPDATE_HOST_ADDRESS: 'update_host_address',
    DUMP_ALL_STATE: 'dump_all_state',
    EMPTY_SALES_QUEUE: 'empty_sales_queue',
};
