export default actionType = {
    HANDLE_AUTHN: 'handle_authn',
    LOGOUT: 'logout',
    SEARCH_TEXT_CHANGED: 'search_text_changed',
    RETURN_SEARCH_ITEMS: 'return_search_items',
    RETURN_EVENTS: 'return_events',
    USERNAME_TEXT_CHANGED: 'username_text_changed',
    PASSWORD_TEXT_CHANGED: 'password_text_changed',
    SET_EVENT: 'set_event',
    UPDATE_USERID: 'update_userid',
    ADD_TO_CART: 'add_to_cart',
    DECREMENT_FROM_CART: 'decrement_from_cart',
    REMOVE_FROM_CART: 'remove_from_cart',
    EMPTY_CART: 'empty_cart',
    CHECKOUT: 'checkout',
    DISCOUNT_KEY_PRESS: 'discount_key_press',
    CLEAR_STATE_ON_LOGOUT: 'clear_state_on_logout',
    UPDATE_SALESQUEUE_ORDER_WITH_ID: 'update_order_with_id',
    REMOVE_FIRST_ITEM_FROM_SALES_QUEUE: 'remove_item_from_sales_queue',
};